In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('train.csv')

In [3]:
df.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

In [4]:
df=pd.get_dummies(df)

In [6]:
train=df[0:7999]

In [7]:
test=df[8000:]

In [8]:
test.head()

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Establishment_Year,Item_Outlet_Sales,Item_Identifier_DRA12,Item_Identifier_DRA24,Item_Identifier_DRA59,Item_Identifier_DRB01,Item_Identifier_DRB13,...,Outlet_Size_High,Outlet_Size_Medium,Outlet_Size_Small,Outlet_Location_Type_Tier 1,Outlet_Location_Type_Tier 2,Outlet_Location_Type_Tier 3,Outlet_Type_Grocery Store,Outlet_Type_Supermarket Type1,Outlet_Type_Supermarket Type2,Outlet_Type_Supermarket Type3
8000,7.02,0.081329,150.0734,2002,4454.2020,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
8001,7.42,0.020388,247.1092,2004,4233.1564,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0
8002,17.25,0.113518,253.5724,1997,5033.4480,0,0,0,0,0,...,0,0,1,1,0,0,0,1,0,0
8003,18.75,0.052917,190.6504,2002,1342.2528,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
8004,20.25,0.018911,220.5772,2007,2446.1492,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0

In [9]:
 x_train=train.drop('Item_Outlet_Sales',axis=1)

In [10]:
y_train=train['Item_Outlet_Sales']

In [12]:
x_test=test.drop('Item_Outlet_Sales',axis=1)

In [13]:
y_test=test['Item_Outlet_Sales']

In [14]:
from sklearn.linear_model import LinearRegression

In [15]:
lreg=LinearRegression()

In [16]:
lreg.fit(x_train,y_train)

ValueError: Input X contains NaN.
LinearRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values